import { launch, type BrowserContext, type Page } from "@cloudflare/playwright";
import { LIMITS, type Env } from "./config";
import { cleanPostText } from "./i18n";

export interface Post { text:string; has_image:boolean; has_video:boolean; image?:Uint8Array }
export interface Comment { author:string; text:string; top?:number }
type Status = "ok"|"user_not_found"|"session_expired"|"no_posts"|"post_not_found"|"all_dead";
type Account = {name:string;cookies:string;hourly_requests:number;hourly_reset:string};
const BASE = (env:Env) => env.BASE_URL || "https://www.threads.com";
const iso=()=>new Date().toISOString();

const COLLECT_POSTS = `() => {
 const posts=[],seen=new Set();
 const containers=document.querySelectorAll('div[data-pressable-container="true"],article,div[role="article"]');
 for(const container of containers){let bestText='',has_image=false,has_video=false;
  for(const img of container.querySelectorAll('img[src*="cdninstagram.com"],img[src*="fbcdn.net"]')){if((img.naturalWidth||img.width||0)>200){has_image=true;break}}
  has_video=container.querySelectorAll('video,div[role="button"] svg[aria-label*="video"],div[role="button"] svg[aria-label="Play"]').length>0;
  for(const el of container.querySelectorAll('span[dir="auto"],div[dir="auto"],span[class*="x1lliihq"]')){const text=(el.innerText||'').trim();if(text.length<20||/^(Follow|Подписаться|Translate|Перевести|See translation|See more|Like|Reply|Repost|Share|Verified|Автор|Ещё|Нравится|Поделиться)/i.test(text)||/^\\d+$/.test(text)||/^\\d{1,2}\\s*[hчдms]$/i.test(text))continue;if(text.length>bestText.length)bestText=text}
  if(bestText.length>25||has_image||has_video){const key=bestText.substring(0,100)+(has_image?'_img':'')+(has_video?'_vid':'');if(!seen.has(key)){seen.add(key);posts.push({text:bestText,has_image,has_video})}}
 } return posts;
}`;

function cookies(raw:string): any[] {
 return (JSON.parse(raw) as Record<string,unknown>[]).map(c=>{let sameSite=String(c.sameSite||"Lax");if(["unspecified","null",""] .includes(sameSite))sameSite="Lax";else if(["no_restriction","none"].includes(sameSite.toLowerCase()))sameSite="None";else sameSite=sameSite[0].toUpperCase()+sameSite.slice(1).toLowerCase();const out:any={name:c.name,value:c.value,domain:c.domain,path:c.path||"/",httpOnly:Boolean(c.httpOnly),secure:c.secure!==false,sameSite};const exp=c.expirationDate??c.expires;if(typeof exp==="number"&&exp>0)out.expires=exp;return out});
}

async function collectPosts(page:Page,target=20):Promise<Post[]>{const all:Post[]=[],seen=new Set<string>();let stall=0;for(let i=0;i<35;i++){const current=await page.evaluate(COLLECT_POSTS) as Post[];let added=0;for(const post of current){const value={...post,text:cleanPostText(post.text)};if(value.text.length<15&&!value.has_image&&!value.has_video)continue;const key=value.text.slice(0,120)+(value.has_image?'_img':'')+(value.has_video?'_vid':'');if(!seen.has(key)){seen.add(key);all.push(value);added++}}if(all.length>=target)break;stall=added?0:stall+1;if(stall>=6)break;await page.evaluate(()=>window.scrollBy(0,1100));await new Promise(r=>setTimeout(r,2300))}return all.slice(0,target)}

async function checkProfile(page:Page,env:Env,username:string):Promise<Status|null>{await page.goto(`${BASE(env)}/@${username}`,{waitUntil:"domcontentloaded",timeout:30_000});await new Promise(r=>setTimeout(r,4000));const body=await page.locator("body").innerText().catch(()=>"");if(["Page not found","Страница не найдена","isn't available","недоступна"].some(x=>body.includes(x)))return "user_not_found";if(page.url().includes("login"))return "session_expired";await page.waitForSelector("span[dir='auto'],div[dir='auto']",{timeout:15_000}).catch(()=>{});return null}

async function chooseAccount(env:Env,tried:string[]):Promise<Account|null>{const cutoff=new Date(Date.now()-3600_000).toISOString();await env.DB.prepare("UPDATE threads_accounts SET hourly_requests=0,hourly_reset=? WHERE hourly_reset<?").bind(iso(),cutoff).run();const marks=tried.map(()=>'?').join(',');const q=`SELECT name,cookies,hourly_requests,hourly_reset FROM threads_accounts WHERE enabled=1 AND is_alive=1 AND hourly_requests<?${tried.length?` AND name NOT IN (${marks})`:''} ORDER BY hourly_requests ASC,RANDOM() LIMIT 1`;return await env.DB.prepare(q).bind(LIMITS.accountHourly,...tried).first<Account>();}
async function mark(env:Env,name:string,ok:boolean,error="",posts=0,cookieData?:string){if(ok)await env.DB.prepare("UPDATE threads_accounts SET is_alive=1,last_error=NULL,requests_count=requests_count+1,posts_sent=posts_sent+?,hourly_requests=hourly_requests+1,last_used=?,updated_at=?,cookies=COALESCE(?,cookies) WHERE name=?").bind(posts,iso(),iso(),cookieData||null,name).run();else await env.DB.prepare("UPDATE threads_accounts SET is_alive=0,last_error=?,errors_count=errors_count+1,updated_at=? WHERE name=?").bind(error.slice(0,500),iso(),name).run()}

async function contextFor(env:Env,account:Account):Promise<{browser:any;context:BrowserContext;page:Page}>{const browser=await launch(env.BROWSER);const context=await browser.newContext({userAgent:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",viewport:{width:680,height:900}});await context.addCookies(cookies(account.cookies));const page=await context.newPage();return{browser,context,page}}

async function capturePosts(page:Page, posts:Post[]):Promise<Post[]>{await page.evaluate(()=>{window.scrollTo(0,0);document.querySelectorAll('div[role="dialog"]').forEach(e=>e.remove());document.querySelectorAll('nav,header').forEach((e:any)=>e.style.display='none')});const result:Post[]=[];for(const post of posts){try{const handle=await page.evaluateHandle((search:string)=>{let nodes=Array.from(document.querySelectorAll('article,div[role="article"]'));if(!nodes.length)nodes=Array.from(document.querySelectorAll('div[data-pressable-container="true"]'));return nodes.find(node=>Array.from(node.querySelectorAll('span[dir="auto"],div[dir="auto"]')).some((b:any)=>(b.innerText||'').trim().startsWith(search)))||null},post.text.slice(0,50));const element=handle.asElement();if(element){await element.scrollIntoViewIfNeeded();const shot=await element.screenshot({type:"png"});result.push({...post,image:new Uint8Array(shot)})}await handle.dispose()}catch{continue}}return result}

export async function fetchPosts(env:Env,username:string,mode:"text"|"img",amount=20):Promise<{data:Post[]|null;status:Status;account?:string}>{const tried:string[]=[];while(true){const acc=await chooseAccount(env,tried);if(!acc)return{data:null,status:"all_dead"};tried.push(acc.name);let opened:any;try{opened=await contextFor(env,acc);const invalid=await checkProfile(opened.page,env,username);if(invalid){if(invalid==="session_expired"){await mark(env,acc.name,false,"Session expired");continue}return{data:null,status:invalid,account:acc.name}}let data=await collectPosts(opened.page,amount);if(!data.length)return{data:null,status:"no_posts",account:acc.name};if(mode==="img")data=await capturePosts(opened.page,data);const updated=JSON.stringify(await opened.context.cookies());await mark(env,acc.name,true,"",data.length,updated);return{data,status:"ok",account:acc.name}}catch(error){await mark(env,acc.name,false,error instanceof Error?error.message:String(error));continue}finally{await opened?.browser.close().catch(()=>{})}}}

async function collectComments(page:Page,target=20):Promise<Comment[]>{const result:Comment[]=[],seen=new Set<string>();let stall=0;await new Promise(r=>setTimeout(r,3000));for(let attempt=0;attempt<20;attempt++){const current=await page.evaluate(() => {const out:any[]=[];for(const container of document.querySelectorAll('div[data-pressable-container="true"]')){const top=(container as HTMLElement).getBoundingClientRect().top+window.scrollY;const link=container.querySelector('a[href^="/@"][role="link"]');const match=(link?.getAttribute('href')||'').match(/\/@([A-Za-z0-9._]+)/);const author=match?'@'+match[1].toLowerCase():'—';let text='';for(const sp of container.querySelectorAll('span[dir="auto"]')){const t=((sp as HTMLElement).innerText||'').trim();if(!t||t.length<3||t.toLowerCase()===author.replace('@','')||/^(Follow|Подписаться|Translate|Перевести|Reply|Ответ|Repost|Share|Send|Like|More|Verified|See translation|Автор|Author|Ещё|Нравится|Поделиться)$/i.test(t)||/^\d+$/.test(t)||/^\d+\s*[hHчмсmsdд]$/.test(t))continue;if(t.length>text.length)text=t}if(text&&/[A-Za-zА-Яа-яÀ-ÿ\u0400-\u04FF\u4e00-\u9fff\u3040-\u30ff]/.test(text))out.push({author,text,top})}out.sort((a,b)=>a.top-b.top);return out.slice(1)}) as Comment[];let added=0;for(const c of current){c.text=cleanPostText(c.text);const key=(c.author+'|'+c.text.slice(0,120)).toLowerCase();if(!seen.has(key)){seen.add(key);result.push(c);added++}}result.sort((a,b)=>(a.top||0)-(b.top||0));if(result.length>=target)break;stall=added?0:stall+1;if(stall>=3)break;await page.evaluate(()=>window.scrollBy(0,1200));await new Promise(r=>setTimeout(r,2500))}return result.slice(0,target)}

export async function fetchComments(env:Env,username:string,index:number,amount=20):Promise<{data:Comment[]|null;status:Status;account?:string}>{const tried:string[]=[];while(true){const acc=await chooseAccount(env,tried);if(!acc)return{data:null,status:"all_dead"};tried.push(acc.name);let opened:any;try{opened=await contextFor(env,acc);const invalid=await checkProfile(opened.page,env,username);if(invalid){if(invalid==="session_expired"){await mark(env,acc.name,false,"Session expired");continue}return{data:null,status:invalid,account:acc.name}}const posts=await collectPosts(opened.page,index+3);if(index>=posts.length)return{data:null,status:"post_not_found",account:acc.name};const search=posts[index].text.slice(0,50);const href=await opened.page.evaluate((s:string)=>{let nodes=Array.from(document.querySelectorAll('article,div[role="article"],div[data-pressable-container="true"]'));for(const post of nodes){if(Array.from(post.querySelectorAll('span[dir="auto"],div[dir="auto"]')).some((b:any)=>(b.innerText||'').trim().startsWith(s))){const a=post.querySelector('a[href*="/post/"]');if(a)return a.getAttribute('href')}}return null},search);if(!href)return{data:null,status:"post_not_found",account:acc.name};await opened.page.goto(href.startsWith('/')?BASE(env)+href:href,{waitUntil:"domcontentloaded",timeout:30_000});await new Promise(r=>setTimeout(r,4000));await opened.page.evaluate(()=>window.scrollBy(0,800));const data=await collectComments(opened.page,amount);const updated=JSON.stringify(await opened.context.cookies());await mark(env,acc.name,true,"",data.length,updated);return{data,status:"ok",account:acc.name}}catch(error){await mark(env,acc.name,false,error instanceof Error?error.message:String(error));continue}finally{await opened?.browser.close().catch(()=>{})}}}

/** Re-opens dead sessions, mirroring the Python bot's reload/periodic health check. */
export async function reviveAccounts(env:Env):Promise<{name:string;ok:boolean}[]>{const rows=(await env.DB.prepare("SELECT name,cookies,hourly_requests,hourly_reset FROM threads_accounts WHERE enabled=1 AND is_alive=0 ORDER BY name").all<Account>()).results,out:{name:string;ok:boolean}[]=[];for(const account of rows){let opened:any;try{opened=await contextFor(env,account);await opened.page.goto(`${BASE(env)}/`,{waitUntil:"domcontentloaded",timeout:30_000});await new Promise(r=>setTimeout(r,3000));const ok=!opened.page.url().includes("login");if(ok){const updated=JSON.stringify(await opened.context.cookies());await env.DB.prepare("UPDATE threads_accounts SET is_alive=1,last_error=NULL,cookies=?,updated_at=? WHERE name=?").bind(updated,iso(),account.name).run()}else await mark(env,account.name,false,"Session expired");out.push({name:account.name,ok})}catch(error){await mark(env,account.name,false,error instanceof Error?error.message:String(error));out.push({name:account.name,ok:false})}finally{await opened?.browser.close().catch(()=>{})}}return out}
